// <auto-generated />
using System;
using BookMovieTicket.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookMovieTicket.Migrations
{
    [DbContext(typeof(MoviesDbContext))]
    [Migration("20240723093927_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookMovieTicket.Models.AuthGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__auth_gro__3213E83FF1BD8F98");

                    b.HasIndex(new[] { "Name" }, "auth_group_name_a6ea08ec_uniq")
                        .IsUnique();

                    b.ToTable("auth_group", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BookMovieTicket.Models.AuthGroupPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("permission_id");

                    b.HasKey("Id")
                        .HasName("PK__auth_gro__3213E83FB09A66FF");

                    b.HasIndex(new[] { "GroupId" }, "auth_group_permissions_group_id_b120cbf9");

                    b.HasIndex(new[] { "GroupId", "PermissionId" }, "auth_group_permissions_group_id_permission_id_0cd325b0_uniq")
                        .IsUnique()
                        .HasFilter("([group_id] IS NOT NULL AND [permission_id] IS NOT NULL)");

                    b.HasIndex(new[] { "PermissionId" }, "auth_group_permissions_permission_id_84c5c92e");

                    b.ToTable("auth_group_permissions", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BookMovieTicket.Models.AuthPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codename")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("codename");

                    b.Property<int>("ContentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("content_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__auth_per__3213E83F031067FE");

                    b.HasIndex(new[] { "ContentTypeId" }, "auth_permission_content_type_id_2f476e4b");

                    b.HasIndex(new[] { "ContentTypeId", "Codename" }, "auth_permission_content_type_id_codename_01ab375a_uniq")
                        .IsUnique()
                        .HasFilter("([content_type_id] IS NOT NULL AND [codename] IS NOT NULL)");

                    b.ToTable("auth_permission", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BookMovieTicket.Models.DjangoAdminLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("ActionFlag")
                        .HasColumnType("smallint")
                        .HasColumnName("action_flag");

                    b.Property<DateTimeOffset>("ActionTime")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("action_time");

                    b.Property<string>("ChangeMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("change_message");

                    b.Property<int?>("ContentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("content_type_id");

                    b.Property<string>("ObjectId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("object_id");

                    b.Property<string>("ObjectRepr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("object_repr");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("char(32)")
                        .HasColumnName("user_id")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK__django_a__3213E83FDAD6135B");

                    b.HasIndex(new[] { "ContentTypeId" }, "django_admin_log_content_type_id_c4bce8eb");

                    b.HasIndex(new[] { "UserId" }, "django_admin_log_user_id_c564eba6");

                    b.ToTable("django_admin_log", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BookMovieTicket.Models.DjangoContentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("app_label");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("model");

                    b.HasKey("Id")
                        .HasName("PK__django_c__3213E83F94A41AC2");

                    b.HasIndex(new[] { "AppLabel", "Model" }, "django_content_type_app_label_model_76bd3d3b_uniq")
                        .IsUnique()
                        .HasFilter("([app_label] IS NOT NULL AND [model] IS NOT NULL)");

                    b.ToTable("django_content_type", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BookMovieTicket.Models.DjangoMigration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("App")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("app");

                    b.Property<DateTimeOffset>("Applied")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("applied");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__django_m__3213E83F714BCCAD");

                    b.ToTable("django_migrations", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BookMovieTicket.Models.DjangoSession", b =>
                {
                    b.Property<string>("SessionKey")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("session_key");

                    b.Property<DateTimeOffset>("ExpireDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("expire_date");

                    b.Property<string>("SessionData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("session_data");

                    b.HasKey("SessionKey")
                        .HasName("PK__django_s__B3BA0F1F4ABC7EB4");

                    b.HasIndex(new[] { "ExpireDate" }, "django_session_expire_date_a5c62663");

                    b.ToTable("django_session", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BookMovieTicket.Models.Movie", b =>
                {
                    b.Property<string>("ImdbId")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("imdb_id");

                    b.Property<string>("PosterPath")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("poster_path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("title");

                    b.Property<string>("WikiLink")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("wiki_link");

                    b.HasKey("ImdbId")
                        .HasName("PK__Movies__F12E201A063D0A05");

                    b.ToTable("Movies", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BookMovieTicket.Models.MovieAdditionalInfo", b =>
                {
                    b.Property<string>("ImdbId")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("imdb_id");

                    b.Property<string>("Actors")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("actors");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("Story")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("story");

                    b.Property<string>("Summary")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("summary");

                    b.Property<string>("Tagline")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tagline");

                    b.Property<string>("WinsNominations")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("wins_nominations");

                    b.HasKey("ImdbId")
                        .HasName("PK__MovieAdd__F12E201AC120E64F");

                    b.ToTable("MovieAdditionalInfo", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BookMovieTicket.Models.MovieDetail", b =>
                {
                    b.Property<string>("ImdbId")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("imdb_id");

                    b.Property<string>("Genres")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("genres");

                    b.Property<bool?>("IsAdult")
                        .HasColumnType("bit")
                        .HasColumnName("is_adult");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("original_title");

                    b.Property<int?>("Runtime")
                        .HasColumnType("int")
                        .HasColumnName("runtime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<int?>("YearOfRelease")
                        .HasColumnType("int")
                        .HasColumnName("year_of_release");

                    b.HasKey("ImdbId")
                        .HasName("PK__MovieDet__F12E201AE5A48D7E");

                    b.ToTable("MovieDetails", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BookMovieTicket.Models.MovieRating", b =>
                {
                    b.Property<string>("ImdbId")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("imdb_id");

                    b.Property<decimal?>("ImdbRating")
                        .HasColumnType("decimal(3, 1)")
                        .HasColumnName("imdb_rating");

                    b.Property<int?>("ImdbVotes")
                        .HasColumnType("int")
                        .HasColumnName("imdb_votes");

                    b.HasKey("ImdbId")
                        .HasName("PK__MovieRat__F12E201A146B6CED");

                    b.ToTable("MovieRatings", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BookMovieTicket.Models.MovieTheater", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsOpen")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<int>("Screens")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MovieTheaters");
                });

            modelBuilder.Entity("BookMovieTicket.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ReservationCode")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<int?>("ScreenShowId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("char(32)");

                    b.HasKey("Id");

                    b.HasIndex("ScreenShowId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("BookMovieTicket.Models.ScreenShowMapper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ScreenId")
                        .HasColumnType("int");

                    b.Property<int?>("ShowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScreenId");

                    b.HasIndex("ShowId");

                    b.ToTable("ScreenShowMappers");
                });

            modelBuilder.Entity("BookMovieTicket.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ScreenId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ScreenId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("BookMovieTicket.Models.Show", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MovieImdbId")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("ShowTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MovieImdbId");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("BookMovieTicket.Models.TheatreScreen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ScreenName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TheaterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TheaterId");

                    b.ToTable("TheatreScreens");
                });

            modelBuilder.Entity("BookMovieTicket.Models.TicketPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("ShowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShowId");

                    b.ToTable("TicketPrices");
                });

            modelBuilder.Entity("BookMovieTicket.Models.UserData", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("char(32)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("DateJoined")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("date_joined");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsStaff")
                        .HasColumnType("bit")
                        .HasColumnName("is_staff");

                    b.Property<bool>("IsSuperuser")
                        .HasColumnType("bit")
                        .HasColumnName("is_superuser");

                    b.Property<DateTimeOffset?>("LastLogin")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_login");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PK__user_dat__3213E83F9CCDDDD9");

                    b.HasIndex(new[] { "PhoneNumber" }, "UQ__user_dat__A1936A6B4A46B413")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "UQ__user_dat__F3DBC5722EBFB4C4")
                        .IsUnique();

                    b.ToTable("user_data", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BookMovieTicket.Models.UserDataGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<string>("UserdataId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("char(32)")
                        .HasColumnName("userdata_id")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK__user_dat__3213E83FD9E5EB9C");

                    b.HasIndex(new[] { "GroupId" }, "user_data_groups_group_id_87f478f6");

                    b.HasIndex(new[] { "UserdataId" }, "user_data_groups_userdata_id_ac66f47c");

                    b.HasIndex(new[] { "UserdataId", "GroupId" }, "user_data_groups_userdata_id_group_id_44f6387f_uniq")
                        .IsUnique()
                        .HasFilter("([userdata_id] IS NOT NULL AND [group_id] IS NOT NULL)");

                    b.ToTable("user_data_groups", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BookMovieTicket.Models.UserDataUserPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("permission_id");

                    b.Property<string>("UserdataId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("char(32)")
                        .HasColumnName("userdata_id")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK__user_dat__3213E83FAAF65E57");

                    b.HasIndex(new[] { "PermissionId" }, "user_data_user_permissions_permission_id_160b9c16");

                    b.HasIndex(new[] { "UserdataId" }, "user_data_user_permissions_userdata_id_d173d91b");

                    b.HasIndex(new[] { "UserdataId", "PermissionId" }, "user_data_user_permissions_userdata_id_permission_id_c133d91d_uniq")
                        .IsUnique()
                        .HasFilter("([userdata_id] IS NOT NULL AND [permission_id] IS NOT NULL)");

                    b.ToTable("user_data_user_permissions", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ReservationSeat", b =>
                {
                    b.Property<int>("ReservationsId")
                        .HasColumnType("int");

                    b.Property<int>("SeatsId")
                        .HasColumnType("int");

                    b.HasKey("ReservationsId", "SeatsId");

                    b.HasIndex("SeatsId");

                    b.ToTable("ReservationSeat");
                });

            modelBuilder.Entity("BookMovieTicket.Models.AuthGroupPermission", b =>
                {
                    b.HasOne("BookMovieTicket.Models.AuthGroup", "Group")
                        .WithMany("AuthGroupPermissions")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("auth_group_permissions_group_id_b120cbf9_fk_auth_group_id");

                    b.HasOne("BookMovieTicket.Models.AuthPermission", "Permission")
                        .WithMany("AuthGroupPermissions")
                        .HasForeignKey("PermissionId")
                        .IsRequired()
                        .HasConstraintName("auth_group_permissions_permission_id_84c5c92e_fk_auth_permission_id");

                    b.Navigation("Group");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("BookMovieTicket.Models.AuthPermission", b =>
                {
                    b.HasOne("BookMovieTicket.Models.DjangoContentType", "ContentType")
                        .WithMany("AuthPermissions")
                        .HasForeignKey("ContentTypeId")
                        .IsRequired()
                        .HasConstraintName("auth_permission_content_type_id_2f476e4b_fk_django_content_type_id");

                    b.Navigation("ContentType");
                });

            modelBuilder.Entity("BookMovieTicket.Models.DjangoAdminLog", b =>
                {
                    b.HasOne("BookMovieTicket.Models.DjangoContentType", "ContentType")
                        .WithMany("DjangoAdminLogs")
                        .HasForeignKey("ContentTypeId")
                        .HasConstraintName("django_admin_log_content_type_id_c4bce8eb_fk_django_content_type_id");

                    b.HasOne("BookMovieTicket.Models.UserData", "User")
                        .WithMany("DjangoAdminLogs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("django_admin_log_user_id_c564eba6_fk_user_data_id");

                    b.Navigation("ContentType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookMovieTicket.Models.MovieAdditionalInfo", b =>
                {
                    b.HasOne("BookMovieTicket.Models.Movie", "Imdb")
                        .WithOne("AdditionalInfo")
                        .HasForeignKey("BookMovieTicket.Models.MovieAdditionalInfo", "ImdbId")
                        .IsRequired()
                        .HasConstraintName("FK__MovieAddi__imdb___787EE5A0");

                    b.Navigation("Imdb");
                });

            modelBuilder.Entity("BookMovieTicket.Models.MovieDetail", b =>
                {
                    b.HasOne("BookMovieTicket.Models.Movie", "Imdb")
                        .WithOne("MovieDetail")
                        .HasForeignKey("BookMovieTicket.Models.MovieDetail", "ImdbId")
                        .IsRequired()
                        .HasConstraintName("FK__MovieDeta__imdb___6FE99F9F");

                    b.Navigation("Imdb");
                });

            modelBuilder.Entity("BookMovieTicket.Models.MovieRating", b =>
                {
                    b.HasOne("BookMovieTicket.Models.Movie", "Imdb")
                        .WithOne("MovieRating")
                        .HasForeignKey("BookMovieTicket.Models.MovieRating", "ImdbId")
                        .IsRequired()
                        .HasConstraintName("FK__MovieRati__imdb___72C60C4A");

                    b.Navigation("Imdb");
                });

            modelBuilder.Entity("BookMovieTicket.Models.Reservation", b =>
                {
                    b.HasOne("BookMovieTicket.Models.ScreenShowMapper", "ScreenShow")
                        .WithMany()
                        .HasForeignKey("ScreenShowId");

                    b.HasOne("BookMovieTicket.Models.UserData", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("ScreenShow");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookMovieTicket.Models.ScreenShowMapper", b =>
                {
                    b.HasOne("BookMovieTicket.Models.TheatreScreen", "Screen")
                        .WithMany()
                        .HasForeignKey("ScreenId");

                    b.HasOne("BookMovieTicket.Models.Show", "Show")
                        .WithMany()
                        .HasForeignKey("ShowId");

                    b.Navigation("Screen");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("BookMovieTicket.Models.Seat", b =>
                {
                    b.HasOne("BookMovieTicket.Models.TheatreScreen", "Screen")
                        .WithMany()
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("BookMovieTicket.Models.Show", b =>
                {
                    b.HasOne("BookMovieTicket.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieImdbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("BookMovieTicket.Models.TheatreScreen", b =>
                {
                    b.HasOne("BookMovieTicket.Models.MovieTheater", "Theater")
                        .WithMany()
                        .HasForeignKey("TheaterId");

                    b.Navigation("Theater");
                });

            modelBuilder.Entity("BookMovieTicket.Models.TicketPrice", b =>
                {
                    b.HasOne("BookMovieTicket.Models.Show", "Show")
                        .WithMany()
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Show");
                });

            modelBuilder.Entity("BookMovieTicket.Models.UserDataGroup", b =>
                {
                    b.HasOne("BookMovieTicket.Models.AuthGroup", "Group")
                        .WithMany("UserDataGroups")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("user_data_groups_group_id_87f478f6_fk_auth_group_id");

                    b.HasOne("BookMovieTicket.Models.UserData", "Userdata")
                        .WithMany("UserDataGroups")
                        .HasForeignKey("UserdataId")
                        .IsRequired()
                        .HasConstraintName("user_data_groups_userdata_id_ac66f47c_fk_user_data_id");

                    b.Navigation("Group");

                    b.Navigation("Userdata");
                });

            modelBuilder.Entity("BookMovieTicket.Models.UserDataUserPermission", b =>
                {
                    b.HasOne("BookMovieTicket.Models.AuthPermission", "Permission")
                        .WithMany("UserDataUserPermissions")
                        .HasForeignKey("PermissionId")
                        .IsRequired()
                        .HasConstraintName("user_data_user_permissions_permission_id_160b9c16_fk_auth_permission_id");

                    b.HasOne("BookMovieTicket.Models.UserData", "Userdata")
                        .WithMany("UserDataUserPermissions")
                        .HasForeignKey("UserdataId")
                        .IsRequired()
                        .HasConstraintName("user_data_user_permissions_userdata_id_d173d91b_fk_user_data_id");

                    b.Navigation("Permission");

                    b.Navigation("Userdata");
                });

            modelBuilder.Entity("ReservationSeat", b =>
                {
                    b.HasOne("BookMovieTicket.Models.Reservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookMovieTicket.Models.Seat", null)
                        .WithMany()
                        .HasForeignKey("SeatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookMovieTicket.Models.AuthGroup", b =>
                {
                    b.Navigation("AuthGroupPermissions");

                    b.Navigation("UserDataGroups");
                });

            modelBuilder.Entity("BookMovieTicket.Models.AuthPermission", b =>
                {
                    b.Navigation("AuthGroupPermissions");

                    b.Navigation("UserDataUserPermissions");
                });

            modelBuilder.Entity("BookMovieTicket.Models.DjangoContentType", b =>
                {
                    b.Navigation("AuthPermissions");

                    b.Navigation("DjangoAdminLogs");
                });

            modelBuilder.Entity("BookMovieTicket.Models.Movie", b =>
                {
                    b.Navigation("AdditionalInfo");

                    b.Navigation("MovieDetail");

                    b.Navigation("MovieRating");
                });

            modelBuilder.Entity("BookMovieTicket.Models.UserData", b =>
                {
                    b.Navigation("DjangoAdminLogs");

                    b.Navigation("UserDataGroups");

                    b.Navigation("UserDataUserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
